# Generated by Django 4.2.30 on 2026-09-08 15:08

import django.contrib.postgres.fields
from django.db import migrations, models


class PostgresOnlyRunSQL(migrations.RunSQL):
    """Keep the PostgreSQL array conversion out of SQLite test databases."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_variant_value_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'IN_STOCK'), ('made_to_order', 'MADE_TO_ORDER'), ('out_of_stock', 'OUT_OF_STOCK')], default='in_stock', max_length=20),
        ),
        # Cannot use AlterField directly because existing rows may have ''
        # (empty string) which Postgres cannot cast to an array literal.
        # This SQL:
        #   1. Clears empty strings to NULL so they become '{}'
        #   2. Casts the column to varchar[] using a USING expression
        PostgresOnlyRunSQL(
            sql="""
                UPDATE products_product SET keywords = NULL WHERE keywords = '' OR keywords IS NULL;
                ALTER TABLE products_product
                    ALTER COLUMN keywords TYPE varchar(100)[]
                    USING CASE
                        WHEN keywords IS NULL THEN ARRAY[]::varchar[]
                        ELSE string_to_array(keywords, ',')
                    END;
                ALTER TABLE products_product ALTER COLUMN keywords SET DEFAULT '{}';
                ALTER TABLE products_product ALTER COLUMN keywords SET NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE products_product
                    ALTER COLUMN keywords TYPE text
                    USING array_to_string(keywords, ',');
                ALTER TABLE products_product ALTER COLUMN keywords SET DEFAULT '';
            """,
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_mode',
            field=models.CharField(choices=[('quote_only', 'QUOTE_ONLY'), ('buy_and_quote', 'BUY_AND_QUOTE'), ('direct_purchase', 'DIRECT_PURCHASE')], default='quote_only', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('active', 'ACTIVE'), ('archived', 'ARCHIVED')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'IN_STOCK'), ('made_to_order', 'MADE_TO_ORDER'), ('out_of_stock', 'OUT_OF_STOCK')], default='in_stock', max_length=20),
        ),
    ]
