# Generated by Django 5.2.17 on 2026-08-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_upload_validating_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope", models.CharField(max_length=80)),
                ("identity_hash", models.CharField(max_length=64)),
                ("window_started_at", models.DateTimeField()),
                ("request_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "window_started_at"],
                        name="rate_limit_scope_window_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "identity_hash"),
                        name="unique_rate_limit_scope_identity",
                    )
                ],
            },
        ),
    ]
