# Generated by Django 4.2.30 on 2026-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_ratelimitbucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='purpose',
            field=models.CharField(choices=[('product_image', 'Product image'), ('category_image', 'Category image'), ('customization_reference', 'Customization reference')], max_length=40),
        ),
    ]
